# CREATE NUMPY ARRAYS WITH RANDOM NUMBERS

* rand() : The function is used to genrate a random values between 0 to 1

* randn() : The function is used to genrate a random value close to zero. This may return positive or negative numbers as well.

* ranf() : The function foe doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0 , 1.0).

* randint() : The function is used to genrate a random nunber between a given number.

# ________________________________________________________________________

# rand() 

The function is used to genrate a random values between 0 to 1

In [10]:
import numpy as np

In [11]:
var1 = np.random.rand(4)
print(var1)

[0.40751409 0.93692168 0.5658004  0.51536684]


In [12]:
var11 = np.random.rand(3 , 3)
print(var11)

[[0.56761096 0.47878573 0.01016912]
 [0.78483364 0.73349474 0.57086251]
 [0.29602071 0.58203394 0.69094977]]


# randn()

The function is used to genrate a random value close to zero. This may return positive or negative numbers as well.

In [13]:
import numpy as np

In [14]:
var2 = np.random.randn(4)
print(var2)

[ 0.67998017 -1.64355262  0.02548934  0.78872268]


In [15]:
var22 = np.random.randn(3 , 3)
print(var22)

[[-0.56817566 -1.62052294 -1.37932156]
 [ 0.89927836 -1.02752524  0.19814976]
 [-0.88833871 -0.49640106  1.74161228]]


# ranf()

The function foe doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0 , 1.0).

In [16]:
import numpy as np

In [17]:
var3 = np.random.ranf(4)
print(var3)

[0.81562441 0.38394802 0.81300666 0.66218992]


# randint()

The function is used to genrate a random nunber between a given number.

In [25]:
var4 = np.random.randint(5 , 222 , 5) # min , max , totalvalues_formate
print(var4)

[147 139  35 116  96]
