SHAPE

In [5]:
import numpy as np
var = np.array([[1 , 2 , 1 , 1 , 1] , [1 , 2 , 1 , 1 , 1]])
print(var)
print()
print(var.shape)

[[1 2 1 1 1]
 [1 2 1 1 1]]

(2, 5)


In [6]:
var1 = np.array([1 , 2 , 3 , 4] , ndmin=4)

print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


RESHAPE

In [10]:
var2 = np.array([1 , 2 , 3 ,1 , 1 , 1 , 4 , 5 , 6])
print(var2)
print()

x = var2.reshape(3 , 3)
print(x)
print(x.ndim)

[1 2 3 1 1 1 4 5 6]

[[1 2 3]
 [1 1 1]
 [4 5 6]]
2


In [39]:
# 3-Dimensional
var3 = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14 , 15 , 16 , 17 , 18])
print(var3)
print()

x1 = var3.reshape(3 , 2  , 3)
print(x1)
print(x1.ndim)

# -----------------------------

one = x1.reshape(-1) # -1 for in one dimension
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1
