# Indexing and slicing

Indexing

In [2]:
import numpy as np

In [3]:
var = np.array([9 , 6 , 54 , 3 , 3])
print(var[2])

54


In [4]:
var1 = np.array([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8]])    # dimension or axis of a numoynnmatrix is starts with 0 like lists that we also learned in previous semster
print(var1.ndim)
print(var1)
print(var1[0 , 2])

2
[[1 2 3 4]
 [5 6 7 8]]
3


In [5]:
var2 = np.array([[[1 , 2] , [1 , 2]]])

print(var2)
print(var2.ndim)
print()
print(var2[0 , 1])

[[[1 2]
  [1 2]]]
3

[1 2]


Slicing

In [6]:
import numpy as np
var = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9])
#               0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8
print(var)
print()
print("2st to 5st : " , var[1 : 5])   # first digit should be zero and last digit should not be included
print("1st to end : " , var[0 : ])  # when we does not write anything at end its mean the array should be print to the last element
print("1st to 8st after 1-1 steps : " , var[0 : 8 : 2])  # 3rd element is the step it should be minimum to hte element like when we write 2 its mean step is of 1 element
print(var[::]) # when we print :: colon it should be print whole array
print("last to start point : " , var[::2]) # its return array from last to start and by step 1 - 1

[1 2 3 4 5 6 7 8 9]

2st to 5st :  [2 3 4 5]
1st to end :  [1 2 3 4 5 6 7 8 9]
1st to 8st after 1-1 steps :  [1 3 5 7]
[1 2 3 4 5 6 7 8 9]
last to start point :  [1 3 5 7 9]
