# Iteration in Numpy

In [30]:
import numpy as np

1-d

In [31]:
var = np.array([9 , 8 , 7 , 6 , 5 , 4 , 3 , 2 , 1])
print(var , "\n" , var.ndim)
print()
for i in var :
    print(i)

[9 8 7 6 5 4 3 2 1] 
 1

9
8
7
6
5
4
3
2
1


2-d

In [32]:
var1 = np.array([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8]])
print(var1 , "\n" , var1.ndim)
print()

for j in var1:
    print(j)

print()

for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]] 
 2

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


3-d

In [33]:
var2 = np.array([[[1 , 2 , 3 , 4] , [1 , 2 , 3 , 4] , [1 , 2 , 3 , 4]]])
print(var2 , "\n" , var2.ndim)
print()

for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]] 
 3

1
2
3
4
1
2
3
4
1
2
3
4


In [34]:
var2 = np.array([[[1 , 2 , 3 , 4] , [1 , 2 , 3 , 4] , [1 , 2 , 3 , 4]]])
print(var2 , "\n" , var2.ndim)
print()

for i in np.nditer(var2 , flags=['buffered'] , op_dtypes=['S']): # nditer is also use as in the place of iteration
    print(i)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]] 
 3

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [38]:
import numpy as np
var2 = np.array([[[1 , 2 , 3 , 4] , [1 , 2 , 3 , 4] , [1 , 2 , 3 , 4]]])
print(var2 , "\n" , var2.ndim)
print()

for a , b in np.ndenumerate(var2):
    print(a , b)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]] 
 3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4
