# Broadcasting in numpy arrays

In [1]:
import numpy as np

In [3]:
var1 = np.array([[1 , 2 , 3]])
print(var1.shape)
print()
print(var1)
print()

print("___________________________________________________________________")
var2 = np.array([[1] , [2] , [3]])
print(var2.shape)
print()
print(var2)
print()


print("___________________________________________________________________")


print(var1 + var2)

(1, 3)

[[1 2 3]]

___________________________________________________________________
(3, 1)

[[1]
 [2]
 [3]]

___________________________________________________________________
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
X = np.array([[1] , [2]])
print(X.shape)
print()
print(X)
print()

print("___________________________________________________________________")
Y = np.array([[1 , 2 , 3] , [1 , 2 , 3]])
print(Y.shape)
print()
print(Y)
print()


print("___________________________________________________________________")


print(X + Y)

(2, 1)

[[1]
 [2]]

___________________________________________________________________
(2, 3)

[[1 2 3]
 [1 2 3]]

___________________________________________________________________
[[2 3 4]
 [3 4 5]]
