# Random numbers in numpy

#### np.random.random()
generates a random number from 0 to 1

In [ ]:
import numpy as np

In [ ]:
print(np.random.random())

0.8621921528885664


In [ ]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.24278032178100195
0.6220459824263357
0.6190628417342964
0.8276616012813612


In [ ]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.2540809132813081
0.5742862896509263
0.9274253242729579
0.9599814581983207


#### np.random.seed()

In [ ]:
np.random.seed(100)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.5434049417909654
0.27836938509379616
0.4245175907491331
0.8447761323199037


In [ ]:
np.random.seed(100)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.5434049417909654
0.27836938509379616
0.4245175907491331
0.8447761323199037


In [ ]:
# you can specify the shape
x = np.random.random((4, 4))
x

array([[0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378],
       [0.81168315, 0.17194101, 0.81622475, 0.27407375]])

#### np.random.randint()

In [ ]:
num = np.random.randint(low = 20, high =100)
num

79

In [ ]:
num = np.random.randint(low = 20, high =100,size = 5)
num

array([87, 27, 69, 67, 85])

In [ ]:
num = np.random.randint(low = 20, high =100,size = (5,5))
num

array([[81, 34, 75, 91, 22],
       [39, 83, 73, 47, 76],
       [50, 68, 67, 59, 58],
       [64, 38, 84, 76, 54],
       [73, 94, 37, 92, 33]])

#### np.random.choice(list_of_choice,num_of_ele)

In [ ]:
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [ ]:
np.random.choice(a,size = 3)

array([27., 82., 35.])

In [ ]:
np.random.choice(a,size = (5,5))

array([[ 22. ,   2.3,  47. ,  82. ,  24. ],
       [ 18. ,  47. , -33. ,  47. ,  35. ],
       [ 25. , -33. ,  47. ,  18. ,  24. ],
       [ 35. ,  35. ,  82. ,  25. , -33. ],
       [-33. ,  22. ,  35. ,  22. ,  25. ]])

## Other Important functions

In [ ]:
x = np.random.random((4, 4))
x

array([[0.14260031, 0.9338413 , 0.94637988, 0.60229666],
       [0.38776628, 0.363188  , 0.20434528, 0.27676506],
       [0.24653588, 0.173608  , 0.96660969, 0.9570126 ],
       [0.59797368, 0.73130075, 0.34038522, 0.0920556 ]])

#### np.round()
rounds an array to given number of decimals

In [ ]:
# to round it to 3 decimal points
rounded = np.round(x, 3)
rounded

array([[0.143, 0.934, 0.946, 0.602],
       [0.388, 0.363, 0.204, 0.277],
       [0.247, 0.174, 0.967, 0.957],
       [0.598, 0.731, 0.34 , 0.092]])

In [ ]:
new = rounded * 100
new

array([[14.3, 93.4, 94.6, 60.2],
       [38.8, 36.3, 20.4, 27.7],
       [24.7, 17.4, 96.7, 95.7],
       [59.8, 73.1, 34. ,  9.2]])

#### astype()
to change the data type of elements

In [ ]:
# to change the data type of elements to integers
intt = new.astype(int)
intt

array([[14, 93, 94, 60],
       [38, 36, 20, 27],
       [24, 17, 96, 95],
       [59, 73, 34,  9]])

In [ ]:
# to change the data type of elements to float
flt = intt.astype(float)
flt

array([[14., 93., 94., 60.],
       [38., 36., 20., 27.],
       [24., 17., 96., 95.],
       [59., 73., 34.,  9.]])

#### reshape()
to reshape an array.

In [ ]:
x = np.arange(32)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
x.shape

(32,)

In [ ]:
x = x.reshape(4,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x.shape

(4, 8)

In [ ]:
x = x.reshape(8,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
x.shape

(8, 4)

In [ ]:
x = x.reshape(2,4,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [ ]:
# to reduce ndarray to 1d array
x = x.reshape(-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
# you know you want 4 rows and not sure about how many columns will be there
x.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
# you know you want 4 columns and not sure about how many rows will be there
x.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

## Some Other Mathematical operations on np arrays

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#np.sin()
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
#np.cos()
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [ ]:
#np.tan()
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [ ]:
#to get the exponential values i,e., e^num
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
#creating and reshaping the array
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### np.sum()
to get the sum of all the elements

In [ ]:
np.sum(a)

45

In [ ]:
# along the column
np.sum(a,axis = 0)

array([12, 15, 18])

In [ ]:
# along the row
np.sum(a,axis = 1)

array([ 6, 15, 24])

#### Transpose

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# dot product
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
# to get the maximum element
a = np.array([1,4,2,6,10,13,5,7,3])
a

array([ 1,  4,  2,  6, 10, 13,  5,  7,  3])

In [ ]:
a.max()

13

In [ ]:
# to get the index at which the maximum element is present
a.argmax()

5

In [ ]:
a

array([ 1,  4,  2,  6, 10, 13,  5,  7,  3])

In [ ]:
#to sort the elements
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7, 10, 13])

In [ ]:
np.argsort(a)

array([0, 2, 8, 1, 6, 3, 7, 4, 5], dtype=int64)