In [21]:
import pandas as pd
file_path = '/content/WineQT - WineQT.csv'
wine_data = pd.read_csv(file_path)
wine_data.head(), wine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB


(   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0            7.4              0.70         0.00             1.9      0.076   
 1            7.8              0.88         0.00             2.6      0.098   
 2            7.8              0.76         0.04             2.3      0.092   
 3           11.2              0.28         0.56             1.9      0.075   
 4            7.4              0.70         0.00             1.9      0.076   
 
    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
 0                 11.0                  34.0   0.9978  3.51       0.56   
 1                 25.0                  67.0   0.9968  3.20       0.68   
 2                 15.0                  54.0   0.9970  3.26       0.65   
 3                 17.0                  60.0   0.9980  3.16       0.58   
 4                 11.0                  34.0   0.9978  3.51       0.56   
 
    alcohol  quality  Id  
 0      9.4        5   0  
 1      9.8       

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
X = wine_data.drop(columns=['quality', 'Id'])
y = (wine_data['quality'] >= 6).astype(int)  # Good wine if quality >= 6
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)
log_reg = LogisticRegression()
log_reg.fit(X_train_pca, y_train)
y_pred = log_reg.predict(X_test_pca)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy, conf_matrix

(0.6855895196506551,
 array([[60, 42],
        [30, 97]]))

In [23]:
pca_5 = PCA(n_components=5)
X_train_pca_5 = pca_5.fit_transform(X_train_scaled)
X_test_pca_5 = pca_5.transform(X_test_scaled)
log_reg_5 = LogisticRegression()
log_reg_5.fit(X_train_pca_5, y_train)
y_pred_5 = log_reg_5.predict(X_test_pca_5)
accuracy_5 = accuracy_score(y_test, y_pred_5)
conf_matrix_5 = confusion_matrix(y_test, y_pred_5)

accuracy_5, conf_matrix_5


(0.74235807860262,
 array([[73, 29],
        [30, 97]]))

In [24]:
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
data=pd.read_csv("/content/WineQT - WineQT.csv")
data.head(10)
X=data.drop(columns=['quality'])
Y=data['quality']
#Standardize data
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
y_scaled=scaler.fit_transform(Y.values.reshape(-1,1))

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
x_train_scaled=scaler.fit_transform(X_train)
x_test_scaled=scaler.fit_transform(X_test)
model=LogisticRegression()
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)
y_pred
accuracy = accuracy_score(Y_test, y_pred)
conf_matrix = confusion_matrix(Y_test, y_pred)
class_report = classification_report(Y_test, y_pred,zero_division=1)




/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [26]:
print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)
pca=PCA(n_components=0.99)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)
x_test_pca.shape

Accuracy: 0.54
Confusion Matrix:
[[ 0  2  4  0  0]
 [ 0 44 52  0  0]
 [ 0 20 79  0  0]
 [ 0  4 22  0  0]
 [ 0  0  2  0  0]]
Classification Report:
              precision    recall  f1-score   support

           4       1.00      0.00      0.00         6
           5       0.63      0.46      0.53        96
           6       0.50      0.80      0.61        99
           7       1.00      0.00      0.00        26
           8       1.00      0.00      0.00         2

    accuracy                           0.54       229
   macro avg       0.83      0.25      0.23       229
weighted avg       0.63      0.54      0.49       229



(229, 11)

In [27]:
model_with_pca=LogisticRegression()
model_with_pca.fit(x_train_pca,Y_train)
y_pred_with_pca=model_with_pca.predict(x_test_pca)
accuracy_with_pca=accuracy_score(Y_test,y_pred_with_pca)
accuracy_with_pca

0.6462882096069869