In [14]:
# TASK -----1

import numpy as np
def array(arr):
    return np.array(arr[::-1] , float)
num = input('Enter the number. for printing reverse numpy array.')
arr = num.strip().split(' ')
result = array(arr)
print(result)

print('Number in input is: ',num)

[-10.  -8.   4.   3.   2.   1.]
Number in input is:  1 2 3 4 -8 -10


In [10]:
# TASK---2

import numpy as np

class NumpyArray:
    def __init__(self, lst, r=0, c=0):
        if r != 0 and c != 0:
            self.lst = np.array(lst).reshape(r, c)
        else:
            self.lst = np.array(lst)

    def disp_mat(self):
        print(self.lst)
# sample numbers / dimension ===>>> 1 2 3 4 5 6 7 8 9 / 3 3
lst1 = list(map(eval, input('Enter the elements for matrix---1: ').split()))
r1, c1 = list(map(eval, input('Enter the dimension for matrix---1::(m * n)').split()))
arr1 = NumpyArray(lst1, r1, c1)
arr1.disp_mat()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# TASK----3

import numpy as np

def main_diagonal(n, m):
    arr = np.zeros((n, m))
    arr[range(n), range(m)] = 1
    return arr
    
n, m = map(int, input('Enter Dimension').strip().split(' '))
result = main_diagonal(n, m)
print(result)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# TASK----3

import numpy as np

N, M = map(int, input('Enter Dimension').split())

# Take input for arrays A and B
A = np.array([list(map(int, input('Enter the number A').split())) for _ in range(N)])
B = np.array([list(map(int, input('Enter the number B').split())) for _ in range(N)])

# Perform operations
print("Addition (A + B):")
print(A + B)

print('------------------------------------------------------')

print("Subtraction (A - B):")
print(A - B)

print('------------------------------------------------------')

print("Multiplication (A * B):")
print(A * B)

print('------------------------------------------------------')

print("Integer Division (A // B):")
print(A // B)

print('------------------------------------------------------')

print("Modulus (A % B):")
print(A % B)

print('------------------------------------------------------')

print("Power (A ** B):")
print(A ** B)

Addition (A + B):
[[ 6  8 10 12]]
------------------------------------------------------
Subtraction (A - B):
[[-4 -4 -4 -4]]
------------------------------------------------------
Multiplication (A * B):
[[ 5 12 21 32]]
------------------------------------------------------
Integer Division (A // B):
[[0 0 0 0]]
------------------------------------------------------
Modulus (A % B):
[[1 2 3 4]]
------------------------------------------------------
Power (A ** B):
[[    1    64  2187 65536]]


In [18]:
# TASK----3

import numpy as np

N, M = map(int, input('Enter the Dimension N * M').split())

matrix = np.array([list(map(int, input('Take input for Number').split())) for _ in range(N)])

print("Transpose of the matrix:")
print(matrix.T)

print('------------------------------------------------------')

print("Flattened matrix:")
print(matrix.flatten())

Transpose of the matrix:
[[1 3]
 [2 4]]
------------------------------------------------------
Flattened matrix:
[1 2 3 4]
