In [7]:
import numpy as np

In [8]:
class NumpyArray:
    def __init__(self, lst, r=0, c=0):
        if r != 0 and c != 0:
            self.lst = np.array(lst).reshape(r, c)
        else:
            self.lst = np.array(lst)

    def __add__(self, other):
        if self.lst.shape == other.lst.shape:
            return NumpyArray(self.lst + other.lst)
        else:
            print("No compatible for Addition...")

    def __sub__(self, other):
        if self.lst.shape == other.lst.shape:
            return NumpyArray(self.lst - other.lst)
        else:
            print("No compatible for Subtraction...")

    def __mul__(self, other):
        if self.lst.shape == other.lst.shape:
            return NumpyArray(self.lst * other.lst)
        else:
            print("No compatible for Multiplication...")

    def dot(self, other):
        if self.lst.shape[1] == other.lst.shape[0]:
            return NumpyArray(np.dot(self.lst, other.lst))
        else:
            print('Dimension is not valid for dot multiplication')

    def disp_mat(self):
        print(self.lst)

lst1 = list(map(eval, input('Enter the elements for matrix---1: ').split()))
r1, c1 = list(map(eval, input('Enter the dimension for matrix---1::(m * n)').split()))
arr1 = NumpyArray(lst1, r1, c1)

lst2 = list(map(eval, input('Enter the elements for matrix---2: ').split()))
r2, c2 = list(map(eval, input('Enter the dimension for matrix---2::(m * n)').split()))
arr2 = NumpyArray(lst2, r2, c2)

In [9]:
print('matrix---1')
arr1.disp_mat()
print(' ')
print('---------------------------')
print(' ')
print('matrix---2')
arr2.disp_mat()

matrix---1
[[1 1]
 [1 1]]
 
---------------------------
 
matrix---2
[[1 1]
 [1 1]]


In [10]:
out = arr1 + arr2
print('Addition of matrix---1 and matrix---2')
out.disp_mat()

Addition of matrix---1 and matrix---2
[[2 2]
 [2 2]]


In [11]:
out = arr1 - arr2
print('Subtraction of matrix---1 and matrix---2')
out.disp_mat()

Subtraction of matrix---1 and matrix---2
[[0 0]
 [0 0]]


In [12]:
out = arr1 * arr2
print('Multiplication of matrix---1 and matrix---2')
out.disp_mat()

Multiplication of matrix---1 and matrix---2
[[1 1]
 [1 1]]


In [13]:
out = arr1.dot(arr2)
print('Dot multiplication of matrix---1 and matrix---2')
out.disp_mat()

Dot multiplication of matrix---1 and matrix---2
[[2 2]
 [2 2]]
