In [11]:
# ARRAY
import numpy as np

x = np.array([1 , 2 , 3 , 4 , 5])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [12]:
l = []
for i in range(1 , 5):
    int_1 = input("enter :")
    l.append(int_1)

print(np.array(l))

['1' '2' '3' '4']


In [13]:
'''
1-D ARRAY == [1 2 3 4]
2-D ARRAY == [[1 2 3 4]]
3-D ARRAY == [[[1 2 3 4]]]
MULTI-D ARRAY == 
'''

'\n1-D ARRAY == [1 2 3 4]\n2-D ARRAY == [[1 2 3 4]]\n3-D ARRAY == [[[1 2 3 4]]]\nMULTI-D ARRAY == \n'

In [24]:
# 1-d
arr1 = np.array([1 , 2 , 3 , 4 , 5])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [25]:
# 2-d
arr2 = np.array([[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 0]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
2


In [26]:
# 3-d
arr3 = np.array([[[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 0] , [7 , 4 ,1 , 8 , 5]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4 5]
  [6 7 8 9 0]
  [7 4 1 8 5]]]
3


In [29]:
arrn = np.array([1,2,3,4],ndmin = 10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
