Importance of Numpy in Python.

In [2]:
# Wide variety of mathematical operations on arrays.
# It supplies an enormous library of high-level mathematical functions that operates on these arrays and matrices.
# Mathematician , Logical , Shape , Manipulation , sorting , selecting , I/O , discrete Fourier transforms , basic linear algebra , basic statistical operations , random simulation and much more.

In [3]:
# ARRAY
import numpy as np

In [4]:
x = np.array([1 , 2 , 3 , 4 , 5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
l = []
for i in range(1 , 5):
    int_1 = input("enter :")
    l.append(int_1)
    
print(np.array(l))

['1' '2' '3' '4']


In [6]:
'''
1-D ARRAY == [1 2 3 4]
2-D ARRAY == [[1 2 3 4]]
3-D ARRAY == [[[1 2 3 4]]]
MULTI-D ARRAY == 
'''

'\n1-D ARRAY == [1 2 3 4]\n2-D ARRAY == [[1 2 3 4]]\n3-D ARRAY == [[[1 2 3 4]]]\nMULTI-D ARRAY == \n'

In [7]:
# 1-d
arr1 = np.array([1 , 2 , 3 , 4 , 5])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [8]:
# 2-d
arr2 = np.array([[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 0]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
2


In [9]:
# 3-d
arr3 = np.array([[[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 0] , [7 , 4 ,1 , 8 , 5]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4 5]
  [6 7 8 9 0]
  [7 4 1 8 5]]]
3


In [10]:
arrn = np.array([1,2,3,4],ndmin = 10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
