SPECIAL NUMPY ARRAY

In [24]:
# array filled with 0's
# array filled with 1's
# create an empty array
# an array with a range of elemnets
# array diagonals elements filled with 1's
# create an array with values that are spaced linearly in a specified interval

In [25]:
import numpy as np

ZEROS

In [26]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((4 , 3))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ONES

In [27]:
ar_one = np.ones(4)
ar_one1 = np.ones((4 , 3))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
