# SPECIAL NUMPY ARRAY

In [9]:
# array filled with 0's
# array filled with 1's
# create an empty array
# an array with a range of elemnets
# array diagonals elements filled with 1's
# create an array with values that are spaced linearly in a specified interval

In [10]:
import numpy as np

ZEROS

In [11]:
# printing zeros elements list
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((4 , 3))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ONES

In [12]:
# printing ones elements list
ar_one = np.ones(4)
ar_one1 = np.ones((4 , 3))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


EMPTY

In [13]:
# printing empty list
# last data value should be printed
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


RANGE

In [14]:
# arrangeing the item in series
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


DIAGONAL

In [23]:
# making diagonal elements filled with 1's
ar_dia = np.eye(8)
print(ar_dia)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


LINE SPACE

In [37]:
ar_lin = np.linspace(0 , 20 , num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
