In [3]:
import numpy as np

arr = np.array({'a' : 10 , 'b' : 20})
print(arr)
print(arr.dtype)
print(type(arr))


{'a': 10, 'b': 20}
object
<class 'numpy.ndarray'>


In [4]:
# ndarray operation

arr = np.arange(1 , 13).reshape(3 , 4)
print("Original array:\n", arr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# sum
out1 = np.sum(arr, axis=0)#SUM     #0 ->> x-axis , 1 ->> y-axis
out2 = np.max(arr, axis=0)#MAXIMUM
print(out1)
print(out2)

[15 18 21 24]
[ 9 10 11 12]


In [22]:
a =  3.523
# priority to even number.
out = round(a)
print(out)

4


In [31]:
a = np.array([3.5 , 2.23 , 1.009])

out3 = np.round(a)
print(out3)

out4 = np.ceil(a) #for ceiling
print(out4)

out5= np.floor(a)#for floor
print(out5)

[4. 2. 1.]
[4. 3. 2.]
[3. 2. 1.]


In [35]:
np.ones((3 , 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
print(np.empty((2 , 5)))

[[9.73996537e-312 2.81617418e-322 1.20953760e-312 1.31370903e-076
  6.50597670e-091]
 [5.15436255e-062 8.26112229e-072 2.17570565e-076 6.48224659e+170
  4.93432906e+257]]


In [54]:
# TASK----5
import numpy as np
N, M = map(int, input('Enter the Dimension N * M').split())
matrix = np.array([list(map(int, input('Take input for Number').split())) for _ in range(N)])


print("Transpose of the matrix:")
print(matrix.T)


print('------------------------------------------------------')


print("Flattened matrix:")
print(matrix.flatten())

Transpose of the matrix:
[[1 3]
 [2 4]]
------------------------------------------------------
Flattened matrix:
[1 2 3 4]
