In [32]:
# TASK -----1

import numpy as np

def arrays(arr):
    return np.array(arr[::-1],float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


In [41]:
# TASK0----2

import numpy as np

class NumpyArray:
    def __init__(self, lst, r=0, c=0):
        if r != 0 and c != 0:
            self.lst = np.array(lst).reshape(r, c)
        else:
            self.lst = np.array(lst)

    def disp_mat(self):
        print(self.lst)

lst1 = list(map(eval, input('Enter the elements for matrix---1: ').split()))
r1, c1 = list(map(eval, input('Enter the dimension for matrix---1::(m * n)').split()))
arr1 = NumpyArray(lst1, r1, c1)
arr1.disp_mat()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# TASK----3

import numpy

def main_diagonal(n, m):
    arr = numpy.zeros((n, m))
    arr[range(n), range(m)] = 1
    return arr
    
n, m = map(int, input().strip().split(' '))
result = main_diagonal(n, m)
print(result)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
